-- MySQL Script generated by MySQL Workbench
-- Dom 26 Nov 2017 00:16:43 -02
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sismo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sismo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sismo` DEFAULT CHARACTER SET utf8 ;
USE `sismo` ;

-- -----------------------------------------------------
-- Table `sismo`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sismo`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NULL,
  `matricula` VARCHAR(255) NULL,
  `email` VARCHAR(255) NULL,
  `curso` VARCHAR(255) NULL,
  `telefone` VARCHAR(15) NULL,
  `hash` VARCHAR(255) NULL,
  `salt` VARCHAR(255) NULL,
  `privilegio` TINYINT(4) NULL,
  `departamento_id` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sismo`.`departamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sismo`.`departamento` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sismo`.`materia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sismo`.`materia` (
  `codigo` INT NOT NULL,
  `nome` VARCHAR(255) NULL,
  `departamento_id` INT NOT NULL,
  PRIMARY KEY (`codigo`),
  INDEX `fk_materia_departamento1_idx` (`departamento_id` ASC),
  CONSTRAINT `fk_materia_departamento1`
    FOREIGN KEY (`departamento_id`)
    REFERENCES `sismo`.`departamento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sismo`.`grupo_estudo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sismo`.`grupo_estudo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NULL,
  `horario` VARCHAR(255) NULL,
  `quantidade_pessoas` INT NULL,
  `descricao` TEXT NULL,
  `materia_departamento_id` INT NOT NULL,
  `usuario_id` INT NOT NULL,
  `materia_codigo` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_grupo_estudo_usuario1_idx` (`usuario_id` ASC),
  INDEX `fk_grupo_estudo_materia1_idx` (`materia_codigo` ASC),
  CONSTRAINT `fk_grupo_estudo_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `sismo`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_grupo_estudo_materia1`
    FOREIGN KEY (`materia_codigo`)
    REFERENCES `sismo`.`materia` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sismo`.`monitorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sismo`.`monitorias` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `turma` VARCHAR(4) NULL,
  `status` INT NULL,
  `materia_codigo` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_monitorias_materia1_idx` (`materia_codigo` ASC),
  CONSTRAINT `fk_monitorias_materia1`
    FOREIGN KEY (`materia_codigo`)
    REFERENCES `sismo`.`materia` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sismo`.`candidatar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sismo`.`candidatar` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `remunerada` INT NULL,
  `agencia` VARCHAR(45) NULL,
  `conta` VARCHAR(45) NULL,
  `banco` VARCHAR(45) NULL,
  `cpf` VARCHAR(14) NULL,
  `status` INT NULL,
  `usuario_id` INT NOT NULL,
  `monitorias_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_candidatar_monitoria_usuario1_idx` (`usuario_id` ASC),
  INDEX `fk_candidatar_monitoria_monitorias1_idx` (`monitorias_id` ASC),
  CONSTRAINT `fk_candidatar_monitoria_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `sismo`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_candidatar_monitoria_monitorias1`
    FOREIGN KEY (`monitorias_id`)
    REFERENCES `sismo`.`monitorias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sismo`.`recuperacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sismo`.`recuperacao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `data_expiracao` DATETIME NULL,
  `token` VARCHAR(255) NULL,
  `usuario_id` INT NOT NULL,
  INDEX `fk_recuperacao_usuario1_idx` (`usuario_id` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_recuperacao_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `sismo`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `sismo`.`cursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sismo`.`cursos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `modalidade` VARCHAR(255) NULL,
  `codigo` INT NULL,
  `denominacao` VARCHAR(255) NULL,
  `turno` VARCHAR(20) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- CURSOS
INSERT INTO `cursos` (`modalidade`, `codigo`, `denominacao`, `turno`) VALUES ('Presencial' , 19, 'ADMINISTRAÇÃO' , 'Diurno'), ('Presencial' , 701, 'ADMINISTRAÇÃO' , 'Noturno'),('Presencial' , 86, 'AGRONOMIA' , 'Diurno'),('Presencial' , 27, 'ARQUITETURA E URBANISMO' , 'Diurno'),('Presencial' , 1422, 'ARQUITETURA E URBANISMO' , 'Noturno'),('Presencial' , 728, 'ARQUIVOLOGIA' , 'Noturno'),('Presencial' , 680, 'ARTES CÊNICAS' , 'Diurno'),('Presencial' , 1309, 'ARTES CÊNICAS' , 'Noturno'),('Presencial' , 671, 'ARTES VISUAIS' , 'Diurno'),('Presencial' , 1023, 'ARTES VISUAIS' , 'Noturno');
INSERT INTO `cursos` (`modalidade`, `codigo`, `denominacao`, `turno`) VALUES ('Presencial' , 191, 'BIBLIOTECONOMIA' , 'Diurno'),('Presencial' , 1538, 'BIOTECNOLOGIA' , 'Diurno'),('Presencial' , 370, 'CIÊNCIA DA COMPUTAÇÃO' , 'Diurno'),('Presencial' , 710, 'CIÊNCIA POLÍTICA' , 'Diurno'),('Presencial' , 1333, 'CIÊNCIAS AMBIENTAIS' , 'Noturno'),('Presencial' , 94, 'CIÊNCIAS BIOLÓGICAS' , 'Diurno'),('Presencial' , 736, 'CIÊNCIAS BIOLÓGICAS' , 'Noturno'),('Presencial' , 507, 'CIÊNCIAS CONTÁBEIS' , 'Diurno'),('Presencial' , 809, 'CIÊNCIAS CONTÁBEIS' , 'Noturno'),('Presencial' , 35, 'CIÊNCIAS ECONÔMICAS' , 'Diurno');
INSERT INTO `cursos` (`modalidade`, `codigo`, `denominacao`, `turno`) VALUES ('Presencial' , 213, 'CIÊNCIAS SOCIAIS' , 'Diurno'),('Presencial' , 906, 'COMPUTAÇÃO' , 'Noturno'),('Presencial' , 205, 'COMUNICAÇÃO SOCIAL' , 'Diurno'),('Presencial' , 1473, 'COMUNICAÇÃO SOCIAL' , 'Noturno'),('Presencial' , 698, 'DESIGN' , 'Diurno'),('Presencial' , 43, 'DIREITO' , 'Diurno'),('Presencial' , 817, 'DIREITO' , 'Noturno'),('Presencial' , 612, 'EDUCAÇÃO ARTÍSTICA' , 'Diurno'),('Presencial' , 795, 'EDUCAÇÃO ARTÍSTICA' , 'Noturno'),('Presencial' , 329, 'EDUCAÇÃO FÍSICA' , 'Diurno');
INSERT INTO `cursos` (`modalidade`, `codigo`, `denominacao`, `turno`) VALUES ('Presencial' , 1589, 'EDUCAÇÃO FÍSICA' , 'Diurno'),('Presencial' , 442, 'ENFERMAGEM' , 'Diurno'),('Presencial' , 1457, 'ENGENHARIA AMBIENTAL' , 'Diurno'),('Presencial' , 582, 'ENGENHARIA CIVIL' , 'Diurno'),('Presencial' , 1341, 'ENGENHARIA DE COMPUTAÇÃO' , 'Diurno'),('Presencial' , 1376, 'ENGENHARIA DE PRODUÇÃO' , 'Noturno'),('Presencial' , 892, 'ENGENHARIA DE REDES DE COMUNICAÇÃO' , 'Diurno'),('Presencial' , 591, 'ENGENHARIA ELÉTRICA' , 'Diurno'),('Presencial' , 396, 'ENGENHARIA FLORESTAL' , 'Diurno'),('Presencial' , 604, 'ENGENHARIA MECÂNICA' , 'Diurno');
INSERT INTO `cursos` (`modalidade`, `codigo`, `denominacao`, `turno`) VALUES ('Presencial' , 949, 'ENGENHARIA MECATRÔNICA' , 'Diurno'),('Presencial' , 1562, 'ENGENHARIA QUÍMICA' , 'Diurno'),('Presencial' , 353, 'ESTATÍSTICA' , 'Diurno'),('Presencial' , 876, 'FARMÁCIA' , 'Diurno'),('Presencial' , 1449, 'FARMÁCIA' , 'Noturno'),('Presencial' , 221, 'FILOSOFIA' , 'Diurno'),('Presencial' , 1503, 'FILOSOFIA' , 'Noturno'),('Presencial' , 124, 'FÍSICA' , 'Diurno'),('Presencial' , 744, 'FÍSICA' , 'Noturno'),('Presencial' , 1384, 'GEOFÍSICA' , 'Diurno');
INSERT INTO `cursos` (`modalidade`, `codigo`, `denominacao`, `turno`) VALUES ('Presencial' , 264, 'GEOGRAFIA' , 'Diurno'),('Presencial' , 132, 'GEOLOGIA' , 'Diurno'),('Presencial' , 1511, 'GESTÃO DE AGRONEGÓCIOS' , 'Noturno'),('Presencial' , 1350, 'GESTÃO DE POLÍTICAS PÚBLICAS' , 'Noturno'),('Presencial' , 230, 'HISTÓRIA' , 'Diurno'),('Presencial' , 1392, 'HISTÓRIA' , 'Noturno'),('Presencial' , 337, 'JORNALISMO' , 'Diurno'),('Presencial' , 51, 'LETRAS' , 'Diurno'),('Presencial' , 779, 'LETRAS' , 'Noturno'),('Presencial' , 825, 'LETRAS' , 'Noturno');
INSERT INTO `cursos` (`modalidade`, `codigo`, `denominacao`, `turno`) VALUES ('Presencial' , 914, 'LETRAS' , 'Noturno'),('Presencial' , 639, 'LETRAS-TRADUÇÃO' , 'Diurno'),('Presencial' , 1414, 'LETRAS-TRADUÇÃO ESPANHOL' , 'Noturno'),('Presencial' , 345, 'LÍNGUA DE SINAIS BRASILEIRA/PORTUGUÊS COMO SEGUNDA LÍNGUA' , 'Diurno'),('Presencial' , 1465, 'LÍNGUAS ESTRANGEIRAS APLICADAS - MSI' , 'Diurno'),('Presencial' , 141, 'MATEMÁTICA' , 'Diurno'),('Presencial' , 752, 'MATEMÁTICA' , 'Noturno'),('Presencial' , 159, 'MEDICINA' , 'Diurno'),('Presencial' , 884, 'MEDICINA VETERINÁRIA' , 'Diurno'),('Presencial' , 1368, 'MUSEOLOGIA' , 'Diurno');
INSERT INTO `cursos` (`modalidade`, `codigo`, `denominacao`, `turno`) VALUES ('Presencial' , 175, 'MÚSICA' , 'Diurno'),('Presencial' , 281, 'MÚSICA' , 'Diurno'),('Presencial' , 1406, 'MÚSICA' , 'Noturno'),('Presencial' , 451, 'NUTRIÇÃO' , 'Diurno'),('Presencial' , 647, 'ODONTOLOGIA' , 'Diurno'),('Presencial' , 60, 'PEDAGOGIA' , 'Diurno'),('Presencial' , 787, 'PEDAGOGIA' , 'Noturno'),('Presencial' , 183, 'PSICOLOGIA' , 'Diurno'),('Presencial' , 167, 'QUÍMICA' , 'Diurno'),('Presencial' , 761, 'QUÍMICA' , 'Noturno'),('Presencial' , 1481, 'QUÍMICA TECNOLÓGICA' , 'Diurno');
INSERT INTO `cursos` (`modalidade`, `codigo`, `denominacao`, `turno`) VALUES ('Presencial' , 400, 'RELAÇÕES INTERNACIONAIS' , 'Diurno'),('Presencial' , 1431, 'SAÚDE COLETIVA' , 'Noturno'),('Presencial' , 272, 'SERVIÇO SOCIAL' , 'Diurno'),('Presencial' , 1490, 'SERVIÇO SOCIAL' , 'Noturno'),('Presencial' , 1554, 'TEORIA, CRÍTICA E HISTÓRIA DA ARTE' , 'Noturno'),('Presencial' , 1520, 'TURISMO' , 'Diurno'),('Distância' , 112, 'ADMINISTRAÇÃO' , 'Diurno'),('Distância' , 1546, 'ADMINISTRAÇÃO PÚBLICA' , 'Diurno'),('Distância' , 1155, 'ARTES VISUAIS' , 'Diurno'),('Distância' , 1325, 'CIÊNCIAS BIOLÓGICAS' , 'Diurno'),('Distância' , 1163, 'EDUCAÇÃO FÍSICA' , 'Diurno');
INSERT INTO `cursos` (`modalidade`, `codigo`, `denominacao`, `turno`) VALUES ('Distância' , 388, 'FÍSICA' , 'Diurno'),('Distância' , 1317, 'GEOGRAFIA' , 'Diurno'),('Distância' , 1147, 'LETRAS' , 'Diurno'),('Distância' , 1139, 'MÚSICA' , 'Diurno'),('Distância' , 1180, 'PEDAGOGIA' , 'Diurno'),('Distância' , 299, 'TEATRO' , 'Diurno'),('Distância' , 1171, 'TEATRO' , 'Diurno');

-- DEPARTAMENTOS
INSERT INTO `departamento` (`id`,`nome`) VALUES (163, "DEPARTAMENTO DE ENGENHARIA ELÉTRICA - ENE");
INSERT INTO `departamento` (`id`,`nome`) VALUES (137, "DEPARTAMENTO DE FILOSOFIA - FIL");
INSERT INTO `departamento` (`id`,`nome`) VALUES (139, "DEPARTAMENTO DE HISTÓRIA - HIS");
INSERT INTO `departamento` (`id`,`nome`) VALUES (113, "DEPARTAMENTO DE MATEMÁTICA - MAT");

-- MATÉRIAS
INSERT INTO `materia`(`codigo`, `nome`, `departamento_id`) VALUES (169676, "COMPUTACAO PARA ENGENHARIA", 163);
INSERT INTO `materia`(`codigo`, `nome`, `departamento_id`) VALUES (167037, "ELETROMAGNETISMO 1", 163);
INSERT INTO `materia`(`codigo`, `nome`, `departamento_id`) VALUES (207624, "FILOSOFIA DA CIÊNCIA", 137);
INSERT INTO `materia`(`codigo`, `nome`, `departamento_id`) VALUES (137987, "MITO E FILOSOFIA", 137);
INSERT INTO `materia`(`codigo`, `nome`, `departamento_id`) VALUES (139203, "HISTÓRIA SOCIAL E POLÍTICA DO BRASIL", 139);
INSERT INTO `materia`(`codigo`, `nome`, `departamento_id`) VALUES (139351, " HISTORIA DA AFRICA", 139);
INSERT INTO `materia`(`codigo`, `nome`, `departamento_id`) VALUES (113018, "MATEMATICA 1", 113);
INSERT INTO `materia`(`codigo`, `nome`, `departamento_id`) VALUES (113069, "VARIAVEL COMPLEXA 1", 113);

-- USUÁRIO ADMINISTRADOR
INSERT INTO `usuario` (`nome`, `email`, `hash`, `privilegio`) VALUES ('Administrador', 'sismo@sismo.com', '$2y$10$EWxwnJp86xfk4eA.QKnnKePyel1CVPKjOp.0jspQA3eQpxmVAOGZm', '3');

-- USUÁRIO CHEFE DE DEPARTAMENTO
INSERT INTO `usuario` (`nome`, `email`, `telefone`, `hash`, `privilegio`, `departamento_id`) VALUES ('João God', 'joaoluiz@pgea.unb.br', '(61) 99999-9999', '$2y$10$yVRUXJvhI0WJ9oidylzoIuOCqGTNgYNt105bKHlMWKceAYqSUu9bm', '2', '163');

-- USUÁRIO FUNCIONÁRIO DE DEPARTAMENTO
INSERT INTO `usuario` (`nome`, `email`, `telefone`, `hash`, `privilegio`, `departamento_id`) VALUES ('Tereza Vieira', 'tereza@unb.br', '(61) 99999-9999', '$2y$10$yVRUXJvhI0WJ9oidylzoIuOCqGTNgYNt105bKHlMWKceAYqSUu9bm', '1', '163');
INSERT INTO `usuario` (`nome`, `email`, `telefone`, `hash`, `privilegio`, `departamento_id`) VALUES ('Fernanda Carvalho', 'fernanda@unb.br', '(61) 99999-9999', '$2y$10$yVRUXJvhI0WJ9oidylzoIuOCqGTNgYNt105bKHlMWKceAYqSUu9bm', '1', '163');
INSERT INTO `usuario` (`nome`, `email`, `telefone`, `hash`, `privilegio`, `departamento_id`) VALUES ('Guilherme Dias', 'guilherme@unb.br', '(61) 99999-9999', '$2y$10$yVRUXJvhI0WJ9oidylzoIuOCqGTNgYNt105bKHlMWKceAYqSUu9bm', '1', '163');

-- USUÁRIO COMUM
INSERT INTO `usuario` (`nome`, `matricula`, `email`, `curso`, `telefone`, `hash`, `privilegio`, `departamento_id`) VALUES ('Phelipe Resende', '16/0141818', 'phelipeuni@gmail.com', '388', '(61) 99999-9999', '$2y$10$yVRUXJvhI0WJ9oidylzoIuOCqGTNgYNt105bKHlMWKceAYqSUu9bm', '0', '113');
